# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `square` gem.
# Please instead update this file by running `bin/tapioca gem square`.


# pkg:gem/square#lib/square.rb:3
module Square; end

# pkg:gem/square#lib/square/connect.rb:2
module Square::Connect; end

# pkg:gem/square#lib/square/connect/bank_account.rb:3
class Square::Connect::BankAccount < ::Square::Connect::Node
  # @return [BankAccount] a new instance of BankAccount
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:6
  def initialize(*args); end

  # Returns the value of attribute account_number_suffix.
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:4
  def account_number_suffix; end

  # Sets the attribute account_number_suffix
  #
  # @param value the value to set the attribute account_number_suffix to.
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:4
  def account_number_suffix=(_arg0); end

  # Returns the value of attribute bank_name.
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:4
  def bank_name; end

  # Sets the attribute bank_name
  #
  # @param value the value to set the attribute bank_name to.
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:4
  def bank_name=(_arg0); end

  # Returns the value of attribute currency_code.
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:4
  def currency_code; end

  # Sets the attribute currency_code
  #
  # @param value the value to set the attribute currency_code to.
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:4
  def currency_code=(_arg0); end

  # Returns the value of attribute merchant.
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:4
  def merchant; end

  # Sets the attribute merchant
  #
  # @param value the value to set the attribute merchant to.
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:4
  def merchant=(_arg0); end

  # Returns the value of attribute name.
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:4
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:4
  def name=(_arg0); end

  # Returns the value of attribute routing_number.
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:4
  def routing_number; end

  # Sets the attribute routing_number
  #
  # @param value the value to set the attribute routing_number to.
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:4
  def routing_number=(_arg0); end

  # Returns the value of attribute type.
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:4
  def type; end

  # Sets the attribute type
  #
  # @param value the value to set the attribute type to.
  #
  # pkg:gem/square#lib/square/connect/bank_account.rb:4
  def type=(_arg0); end
end

# pkg:gem/square#lib/square/connect/connections.rb:3
module Square::Connect::Connections; end

# pkg:gem/square#lib/square/connect/connections/bank_accounts.rb:4
module Square::Connect::Connections::BankAccounts
  # pkg:gem/square#lib/square/connect/connections/bank_accounts.rb:5
  def bank_account(bank_account_id, params = T.unsafe(nil)); end
end

# pkg:gem/square#lib/square/connect/connections/payments.rb:4
module Square::Connect::Connections::Payments
  # pkg:gem/square#lib/square/connect/connections/payments.rb:17
  def payment(payment_id, params = T.unsafe(nil)); end

  # pkg:gem/square#lib/square/connect/connections/payments.rb:5
  def payments(params = T.unsafe(nil)); end
end

# pkg:gem/square#lib/square/connect/connections/refunds.rb:4
module Square::Connect::Connections::Refunds
  # pkg:gem/square#lib/square/connect/connections/refunds.rb:5
  def refunds(params = T.unsafe(nil)); end
end

# pkg:gem/square#lib/square/connect/connections/settlements.rb:4
module Square::Connect::Connections::Settlements
  # pkg:gem/square#lib/square/connect/connections/settlements.rb:17
  def settlement(settlement_id, params = T.unsafe(nil)); end

  # pkg:gem/square#lib/square/connect/connections/settlements.rb:5
  def settlements(params = T.unsafe(nil)); end
end

# pkg:gem/square#lib/square/connect/device.rb:3
class Square::Connect::Device
  # @return [Device] a new instance of Device
  #
  # pkg:gem/square#lib/square/connect/device.rb:6
  def initialize(attributes = T.unsafe(nil)); end

  # Returns the value of attribute identifier.
  #
  # pkg:gem/square#lib/square/connect/device.rb:4
  def identifier; end

  # Sets the attribute identifier
  #
  # @param value the value to set the attribute identifier to.
  #
  # pkg:gem/square#lib/square/connect/device.rb:4
  def identifier=(_arg0); end

  # Returns the value of attribute name.
  #
  # pkg:gem/square#lib/square/connect/device.rb:4
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # pkg:gem/square#lib/square/connect/device.rb:4
  def name=(_arg0); end
end

# pkg:gem/square#lib/square/connect/discount.rb:3
class Square::Connect::Discount
  # @return [Discount] a new instance of Discount
  #
  # pkg:gem/square#lib/square/connect/discount.rb:6
  def initialize(attributes = T.unsafe(nil)); end

  # Returns the value of attribute applied_money.
  #
  # pkg:gem/square#lib/square/connect/discount.rb:4
  def applied_money; end

  # Sets the attribute applied_money
  #
  # @param value the value to set the attribute applied_money to.
  #
  # pkg:gem/square#lib/square/connect/discount.rb:4
  def applied_money=(_arg0); end

  # Returns the value of attribute name.
  #
  # pkg:gem/square#lib/square/connect/discount.rb:4
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # pkg:gem/square#lib/square/connect/discount.rb:4
  def name=(_arg0); end
end

# pkg:gem/square#lib/square/connect/error.rb:3
class Square::Connect::Error < ::StandardError
  # @return [Error] a new instance of Error
  #
  # pkg:gem/square#lib/square/connect/error.rb:6
  def initialize(status, error); end

  # Returns the value of attribute status.
  #
  # pkg:gem/square#lib/square/connect/error.rb:4
  def status; end

  # Sets the attribute status
  #
  # @param value the value to set the attribute status to.
  #
  # pkg:gem/square#lib/square/connect/error.rb:4
  def status=(_arg0); end

  # Returns the value of attribute type.
  #
  # pkg:gem/square#lib/square/connect/error.rb:4
  def type; end

  # Sets the attribute type
  #
  # @param value the value to set the attribute type to.
  #
  # pkg:gem/square#lib/square/connect/error.rb:4
  def type=(_arg0); end
end

# pkg:gem/square#lib/square/connect/item_detail.rb:3
class Square::Connect::ItemDetail
  # @return [ItemDetail] a new instance of ItemDetail
  #
  # pkg:gem/square#lib/square/connect/item_detail.rb:6
  def initialize(attributes = T.unsafe(nil)); end

  # Returns the value of attribute category_name.
  #
  # pkg:gem/square#lib/square/connect/item_detail.rb:4
  def category_name; end

  # Sets the attribute category_name
  #
  # @param value the value to set the attribute category_name to.
  #
  # pkg:gem/square#lib/square/connect/item_detail.rb:4
  def category_name=(_arg0); end

  # Returns the value of attribute sku.
  #
  # pkg:gem/square#lib/square/connect/item_detail.rb:4
  def sku; end

  # Sets the attribute sku
  #
  # @param value the value to set the attribute sku to.
  #
  # pkg:gem/square#lib/square/connect/item_detail.rb:4
  def sku=(_arg0); end
end

# pkg:gem/square#lib/square/connect/itemization.rb:3
class Square::Connect::Itemization
  # @return [Itemization] a new instance of Itemization
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:6
  def initialize(attributes = T.unsafe(nil)); end

  # Returns the value of attribute discount_money.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def discount_money; end

  # Sets the attribute discount_money
  #
  # @param value the value to set the attribute discount_money to.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def discount_money=(_arg0); end

  # Returns the value of attribute discounts.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def discounts; end

  # Sets the attribute discounts
  #
  # @param value the value to set the attribute discounts to.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def discounts=(_arg0); end

  # Returns the value of attribute gross_sales_money.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def gross_sales_money; end

  # Sets the attribute gross_sales_money
  #
  # @param value the value to set the attribute gross_sales_money to.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def gross_sales_money=(_arg0); end

  # Returns the value of attribute item_detail.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def item_detail; end

  # Sets the attribute item_detail
  #
  # @param value the value to set the attribute item_detail to.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def item_detail=(_arg0); end

  # Returns the value of attribute item_variation_name.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def item_variation_name; end

  # Sets the attribute item_variation_name
  #
  # @param value the value to set the attribute item_variation_name to.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def item_variation_name=(_arg0); end

  # Returns the value of attribute name.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def name=(_arg0); end

  # Returns the value of attribute notes.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def notes; end

  # Sets the attribute notes
  #
  # @param value the value to set the attribute notes to.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def notes=(_arg0); end

  # Returns the value of attribute quantity.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def quantity; end

  # Sets the attribute quantity
  #
  # @param value the value to set the attribute quantity to.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def quantity=(_arg0); end

  # Returns the value of attribute single_quantity_money.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def single_quantity_money; end

  # Sets the attribute single_quantity_money
  #
  # @param value the value to set the attribute single_quantity_money to.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def single_quantity_money=(_arg0); end

  # Returns the value of attribute taxes.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def taxes; end

  # Sets the attribute taxes
  #
  # @param value the value to set the attribute taxes to.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def taxes=(_arg0); end

  # Returns the value of attribute total_money.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def total_money; end

  # Sets the attribute total_money
  #
  # @param value the value to set the attribute total_money to.
  #
  # pkg:gem/square#lib/square/connect/itemization.rb:4
  def total_money=(_arg0); end
end

# pkg:gem/square#lib/square/connect/merchant.rb:3
class Square::Connect::Merchant < ::Square::Connect::Node
  include ::Square::Connect::Connections::Payments
  include ::Square::Connect::Connections::Refunds
  include ::Square::Connect::Connections::Settlements
  include ::Square::Connect::Connections::BankAccounts

  # @return [Merchant] a new instance of Merchant
  #
  # pkg:gem/square#lib/square/connect/merchant.rb:11
  def initialize(*args); end

  # Returns the value of attribute country_code.
  #
  # pkg:gem/square#lib/square/connect/merchant.rb:9
  def country_code; end

  # Sets the attribute country_code
  #
  # @param value the value to set the attribute country_code to.
  #
  # pkg:gem/square#lib/square/connect/merchant.rb:9
  def country_code=(_arg0); end

  # Returns the value of attribute email.
  #
  # pkg:gem/square#lib/square/connect/merchant.rb:9
  def email; end

  # Sets the attribute email
  #
  # @param value the value to set the attribute email to.
  #
  # pkg:gem/square#lib/square/connect/merchant.rb:9
  def email=(_arg0); end

  # Returns the value of attribute language_code.
  #
  # pkg:gem/square#lib/square/connect/merchant.rb:9
  def language_code; end

  # Sets the attribute language_code
  #
  # @param value the value to set the attribute language_code to.
  #
  # pkg:gem/square#lib/square/connect/merchant.rb:9
  def language_code=(_arg0); end

  # Returns the value of attribute name.
  #
  # pkg:gem/square#lib/square/connect/merchant.rb:9
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # pkg:gem/square#lib/square/connect/merchant.rb:9
  def name=(_arg0); end

  class << self
    # pkg:gem/square#lib/square/connect/merchant.rb:21
    def me(access_token); end
  end
end

# pkg:gem/square#lib/square/connect/money.rb:3
class Square::Connect::Money
  # @return [Money] a new instance of Money
  #
  # pkg:gem/square#lib/square/connect/money.rb:6
  def initialize(attributes = T.unsafe(nil)); end

  # Returns the value of attribute amount.
  #
  # pkg:gem/square#lib/square/connect/money.rb:4
  def amount; end

  # Sets the attribute amount
  #
  # @param value the value to set the attribute amount to.
  #
  # pkg:gem/square#lib/square/connect/money.rb:4
  def amount=(_arg0); end

  # Returns the value of attribute currency_code.
  #
  # pkg:gem/square#lib/square/connect/money.rb:4
  def currency_code; end

  # Sets the attribute currency_code
  #
  # @param value the value to set the attribute currency_code to.
  #
  # pkg:gem/square#lib/square/connect/money.rb:4
  def currency_code=(_arg0); end
end

# pkg:gem/square#lib/square/connect/node.rb:3
class Square::Connect::Node
  # @return [Node] a new instance of Node
  # @yield [attributes]
  #
  # pkg:gem/square#lib/square/connect/node.rb:6
  def initialize(*args); end

  # Returns the value of attribute access_token.
  #
  # pkg:gem/square#lib/square/connect/node.rb:4
  def access_token; end

  # Sets the attribute access_token
  #
  # @param value the value to set the attribute access_token to.
  #
  # pkg:gem/square#lib/square/connect/node.rb:4
  def access_token=(_arg0); end

  # Returns the value of attribute endpoint.
  #
  # pkg:gem/square#lib/square/connect/node.rb:4
  def endpoint; end

  # Sets the attribute endpoint
  #
  # @param value the value to set the attribute endpoint to.
  #
  # pkg:gem/square#lib/square/connect/node.rb:4
  def endpoint=(_arg0); end

  # pkg:gem/square#lib/square/connect/node.rb:14
  def fetch; end

  # Returns the value of attribute identifier.
  #
  # pkg:gem/square#lib/square/connect/node.rb:4
  def identifier; end

  # Sets the attribute identifier
  #
  # @param value the value to set the attribute identifier to.
  #
  # pkg:gem/square#lib/square/connect/node.rb:4
  def identifier=(_arg0); end

  private

  # @raise [Exception]
  #
  # pkg:gem/square#lib/square/connect/node.rb:26
  def access_token_required!; end

  # pkg:gem/square#lib/square/connect/node.rb:30
  def endpoint_for(*path_elements); end

  # @raise [Error]
  #
  # pkg:gem/square#lib/square/connect/node.rb:57
  def handle_error_response(response); end

  # pkg:gem/square#lib/square/connect/node.rb:43
  def handle_response; end

  # pkg:gem/square#lib/square/connect/node.rb:53
  def handle_success_response(response); end

  # pkg:gem/square#lib/square/connect/node.rb:62
  def parse_json(raw_json); end

  # pkg:gem/square#lib/square/connect/node.rb:34
  def tokenize(access_token); end
end

# pkg:gem/square#lib/square/connect/payment.rb:3
class Square::Connect::Payment < ::Square::Connect::Node
  # @return [Payment] a new instance of Payment
  #
  # pkg:gem/square#lib/square/connect/payment.rb:26
  def initialize(*args); end

  # Returns the value of attribute additive_tax.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def additive_tax; end

  # Sets the attribute additive_tax
  #
  # @param value the value to set the attribute additive_tax to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def additive_tax=(_arg0); end

  # Returns the value of attribute additive_tax_money.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def additive_tax_money; end

  # Sets the attribute additive_tax_money
  #
  # @param value the value to set the attribute additive_tax_money to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def additive_tax_money=(_arg0); end

  # Returns the value of attribute created_at.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def created_at; end

  # Sets the attribute created_at
  #
  # @param value the value to set the attribute created_at to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def created_at=(_arg0); end

  # Returns the value of attribute creator.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def creator; end

  # Sets the attribute creator
  #
  # @param value the value to set the attribute creator to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def creator=(_arg0); end

  # Returns the value of attribute description.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def description; end

  # Sets the attribute description
  #
  # @param value the value to set the attribute description to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def description=(_arg0); end

  # Returns the value of attribute device.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def device; end

  # Sets the attribute device
  #
  # @param value the value to set the attribute device to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def device=(_arg0); end

  # Returns the value of attribute discount_money.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def discount_money; end

  # Sets the attribute discount_money
  #
  # @param value the value to set the attribute discount_money to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def discount_money=(_arg0); end

  # Returns the value of attribute inclusive_tax.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def inclusive_tax; end

  # Sets the attribute inclusive_tax
  #
  # @param value the value to set the attribute inclusive_tax to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def inclusive_tax=(_arg0); end

  # Returns the value of attribute inclusive_tax_money.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def inclusive_tax_money; end

  # Sets the attribute inclusive_tax_money
  #
  # @param value the value to set the attribute inclusive_tax_money to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def inclusive_tax_money=(_arg0); end

  # Returns the value of attribute itemizations.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def itemizations; end

  # Sets the attribute itemizations
  #
  # @param value the value to set the attribute itemizations to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def itemizations=(_arg0); end

  # Returns the value of attribute merchant.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def merchant; end

  # Sets the attribute merchant
  #
  # @param value the value to set the attribute merchant to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def merchant=(_arg0); end

  # Returns the value of attribute net_total_money.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def net_total_money; end

  # Sets the attribute net_total_money
  #
  # @param value the value to set the attribute net_total_money to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def net_total_money=(_arg0); end

  # Returns the value of attribute processing_fee_money.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def processing_fee_money; end

  # Sets the attribute processing_fee_money
  #
  # @param value the value to set the attribute processing_fee_money to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def processing_fee_money=(_arg0); end

  # Returns the value of attribute refunded_money.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def refunded_money; end

  # Sets the attribute refunded_money
  #
  # @param value the value to set the attribute refunded_money to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def refunded_money=(_arg0); end

  # Returns the value of attribute refunds.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def refunds; end

  # Sets the attribute refunds
  #
  # @param value the value to set the attribute refunds to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def refunds=(_arg0); end

  # Returns the value of attribute tax_money.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def tax_money; end

  # Sets the attribute tax_money
  #
  # @param value the value to set the attribute tax_money to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def tax_money=(_arg0); end

  # Returns the value of attribute tender.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def tender; end

  # Sets the attribute tender
  #
  # @param value the value to set the attribute tender to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def tender=(_arg0); end

  # Returns the value of attribute tip_money.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def tip_money; end

  # Sets the attribute tip_money
  #
  # @param value the value to set the attribute tip_money to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def tip_money=(_arg0); end

  # Returns the value of attribute total_collected_money.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def total_collected_money; end

  # Sets the attribute total_collected_money
  #
  # @param value the value to set the attribute total_collected_money to.
  #
  # pkg:gem/square#lib/square/connect/payment.rb:4
  def total_collected_money=(_arg0); end
end

# pkg:gem/square#lib/square/connect.rb:3
Square::Connect::ROOT_URL = T.let(T.unsafe(nil), String)

# pkg:gem/square#lib/square/connect/refund.rb:3
class Square::Connect::Refund
  # @return [Refund] a new instance of Refund
  #
  # pkg:gem/square#lib/square/connect/refund.rb:6
  def initialize(attributes = T.unsafe(nil)); end

  # Returns the value of attribute created_at.
  #
  # pkg:gem/square#lib/square/connect/refund.rb:4
  def created_at; end

  # Sets the attribute created_at
  #
  # @param value the value to set the attribute created_at to.
  #
  # pkg:gem/square#lib/square/connect/refund.rb:4
  def created_at=(_arg0); end

  # Returns the value of attribute identifier.
  #
  # pkg:gem/square#lib/square/connect/refund.rb:4
  def identifier; end

  # Sets the attribute identifier
  #
  # @param value the value to set the attribute identifier to.
  #
  # pkg:gem/square#lib/square/connect/refund.rb:4
  def identifier=(_arg0); end

  # Returns the value of attribute payment.
  #
  # pkg:gem/square#lib/square/connect/refund.rb:4
  def payment; end

  # Sets the attribute payment
  #
  # @param value the value to set the attribute payment to.
  #
  # pkg:gem/square#lib/square/connect/refund.rb:4
  def payment=(_arg0); end

  # Returns the value of attribute processed_at.
  #
  # pkg:gem/square#lib/square/connect/refund.rb:4
  def processed_at; end

  # Sets the attribute processed_at
  #
  # @param value the value to set the attribute processed_at to.
  #
  # pkg:gem/square#lib/square/connect/refund.rb:4
  def processed_at=(_arg0); end

  # Returns the value of attribute reason.
  #
  # pkg:gem/square#lib/square/connect/refund.rb:4
  def reason; end

  # Sets the attribute reason
  #
  # @param value the value to set the attribute reason to.
  #
  # pkg:gem/square#lib/square/connect/refund.rb:4
  def reason=(_arg0); end

  # Returns the value of attribute refunded_money.
  #
  # pkg:gem/square#lib/square/connect/refund.rb:4
  def refunded_money; end

  # Sets the attribute refunded_money
  #
  # @param value the value to set the attribute refunded_money to.
  #
  # pkg:gem/square#lib/square/connect/refund.rb:4
  def refunded_money=(_arg0); end

  # Returns the value of attribute type.
  #
  # pkg:gem/square#lib/square/connect/refund.rb:4
  def type; end

  # Sets the attribute type
  #
  # @param value the value to set the attribute type to.
  #
  # pkg:gem/square#lib/square/connect/refund.rb:4
  def type=(_arg0); end
end

# pkg:gem/square#lib/square/connect/settlement.rb:3
class Square::Connect::Settlement < ::Square::Connect::Node
  # @return [Settlement] a new instance of Settlement
  #
  # pkg:gem/square#lib/square/connect/settlement.rb:6
  def initialize(*args); end

  # Returns the value of attribute bank_account.
  #
  # pkg:gem/square#lib/square/connect/settlement.rb:4
  def bank_account; end

  # Sets the attribute bank_account
  #
  # @param value the value to set the attribute bank_account to.
  #
  # pkg:gem/square#lib/square/connect/settlement.rb:4
  def bank_account=(_arg0); end

  # Returns the value of attribute entries.
  #
  # pkg:gem/square#lib/square/connect/settlement.rb:4
  def entries; end

  # Sets the attribute entries
  #
  # @param value the value to set the attribute entries to.
  #
  # pkg:gem/square#lib/square/connect/settlement.rb:4
  def entries=(_arg0); end

  # Returns the value of attribute initiated_at.
  #
  # pkg:gem/square#lib/square/connect/settlement.rb:4
  def initiated_at; end

  # Sets the attribute initiated_at
  #
  # @param value the value to set the attribute initiated_at to.
  #
  # pkg:gem/square#lib/square/connect/settlement.rb:4
  def initiated_at=(_arg0); end

  # Returns the value of attribute status.
  #
  # pkg:gem/square#lib/square/connect/settlement.rb:4
  def status; end

  # Sets the attribute status
  #
  # @param value the value to set the attribute status to.
  #
  # pkg:gem/square#lib/square/connect/settlement.rb:4
  def status=(_arg0); end

  # Returns the value of attribute total_money.
  #
  # pkg:gem/square#lib/square/connect/settlement.rb:4
  def total_money; end

  # Sets the attribute total_money
  #
  # @param value the value to set the attribute total_money to.
  #
  # pkg:gem/square#lib/square/connect/settlement.rb:4
  def total_money=(_arg0); end
end

# pkg:gem/square#lib/square/connect/tax.rb:3
class Square::Connect::Tax
  # @return [Tax] a new instance of Tax
  #
  # pkg:gem/square#lib/square/connect/tax.rb:6
  def initialize(attributes = T.unsafe(nil)); end

  # Returns the value of attribute applied_money.
  #
  # pkg:gem/square#lib/square/connect/tax.rb:4
  def applied_money; end

  # Sets the attribute applied_money
  #
  # @param value the value to set the attribute applied_money to.
  #
  # pkg:gem/square#lib/square/connect/tax.rb:4
  def applied_money=(_arg0); end

  # Returns the value of attribute inclusion_type.
  #
  # pkg:gem/square#lib/square/connect/tax.rb:4
  def inclusion_type; end

  # Sets the attribute inclusion_type
  #
  # @param value the value to set the attribute inclusion_type to.
  #
  # pkg:gem/square#lib/square/connect/tax.rb:4
  def inclusion_type=(_arg0); end

  # Returns the value of attribute name.
  #
  # pkg:gem/square#lib/square/connect/tax.rb:4
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # pkg:gem/square#lib/square/connect/tax.rb:4
  def name=(_arg0); end

  # Returns the value of attribute rate.
  #
  # pkg:gem/square#lib/square/connect/tax.rb:4
  def rate; end

  # Sets the attribute rate
  #
  # @param value the value to set the attribute rate to.
  #
  # pkg:gem/square#lib/square/connect/tax.rb:4
  def rate=(_arg0); end
end

# pkg:gem/square#lib/square/connect/tender.rb:3
class Square::Connect::Tender
  # @return [Tender] a new instance of Tender
  #
  # pkg:gem/square#lib/square/connect/tender.rb:6
  def initialize(attributes = T.unsafe(nil)); end

  # Returns the value of attribute card_brand.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def card_brand; end

  # Sets the attribute card_brand
  #
  # @param value the value to set the attribute card_brand to.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def card_brand=(_arg0); end

  # Returns the value of attribute change_back_money.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def change_back_money; end

  # Sets the attribute change_back_money
  #
  # @param value the value to set the attribute change_back_money to.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def change_back_money=(_arg0); end

  # Returns the value of attribute entry_method.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def entry_method; end

  # Sets the attribute entry_method
  #
  # @param value the value to set the attribute entry_method to.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def entry_method=(_arg0); end

  # Returns the value of attribute name.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def name=(_arg0); end

  # Returns the value of attribute pan_suffix.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def pan_suffix; end

  # Sets the attribute pan_suffix
  #
  # @param value the value to set the attribute pan_suffix to.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def pan_suffix=(_arg0); end

  # Returns the value of attribute payment_note.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def payment_note; end

  # Sets the attribute payment_note
  #
  # @param value the value to set the attribute payment_note to.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def payment_note=(_arg0); end

  # Returns the value of attribute tendered_money.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def tendered_money; end

  # Sets the attribute tendered_money
  #
  # @param value the value to set the attribute tendered_money to.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def tendered_money=(_arg0); end

  # Returns the value of attribute total_money.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def total_money; end

  # Sets the attribute total_money
  #
  # @param value the value to set the attribute total_money to.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def total_money=(_arg0); end

  # Returns the value of attribute type.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def type; end

  # Sets the attribute type
  #
  # @param value the value to set the attribute type to.
  #
  # pkg:gem/square#lib/square/connect/tender.rb:4
  def type=(_arg0); end
end

# pkg:gem/square#lib/square/exception.rb:2
class Square::Exception < ::StandardError; end

# pkg:gem/square#lib/square/oauth2.rb:2
module Square::OAuth2; end

# pkg:gem/square#lib/square/oauth2/access_token.rb:3
class Square::OAuth2::AccessToken < ::Rack::OAuth2::AccessToken::Bearer
  # @return [AccessToken] a new instance of AccessToken
  #
  # pkg:gem/square#lib/square/oauth2/access_token.rb:4
  def initialize(*options); end

  # pkg:gem/square#lib/square/oauth2/access_token.rb:3
  def access_token; end

  # pkg:gem/square#lib/square/oauth2/access_token.rb:3
  def access_token=(_arg0); end

  # pkg:gem/square#lib/square/oauth2/access_token.rb:3
  def expires_in; end

  # pkg:gem/square#lib/square/oauth2/access_token.rb:3
  def expires_in=(_arg0); end

  # pkg:gem/square#lib/square/oauth2/access_token.rb:3
  def refresh_token; end

  # pkg:gem/square#lib/square/oauth2/access_token.rb:3
  def refresh_token=(_arg0); end

  # pkg:gem/square#lib/square/oauth2/access_token.rb:3
  def scope; end

  # pkg:gem/square#lib/square/oauth2/access_token.rb:3
  def scope=(_arg0); end

  # pkg:gem/square#lib/square/oauth2/access_token.rb:3
  def token_type; end

  # pkg:gem/square#lib/square/oauth2/access_token.rb:3
  def token_type=(_arg0); end
end

# pkg:gem/square#lib/square/oauth2/client.rb:3
class Square::OAuth2::Client < ::Rack::OAuth2::Client
  # @return [Client] a new instance of Client
  #
  # pkg:gem/square#lib/square/oauth2/client.rb:4
  def initialize(*options); end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def authorization_endpoint; end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def authorization_endpoint=(_arg0); end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def certificate; end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def certificate=(_arg0); end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def host; end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def host=(_arg0); end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def identifier; end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def identifier=(_arg0); end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def port; end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def port=(_arg0); end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def private_key; end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def private_key=(_arg0); end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def redirect_uri; end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def redirect_uri=(_arg0); end

  # pkg:gem/square#lib/square/oauth2/client.rb:12
  def renew!; end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def revocation_endpoint; end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def revocation_endpoint=(_arg0); end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def scheme; end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def scheme=(_arg0); end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def secret; end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def secret=(_arg0); end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def token_endpoint; end

  # pkg:gem/square#lib/square/oauth2/client.rb:3
  def token_endpoint=(_arg0); end

  private

  # pkg:gem/square#lib/square/oauth2/client.rb:18
  def handle_success_response(response); end
end

# pkg:gem/square#lib/square/oauth2.rb:3
Square::OAuth2::ROOT_URL = T.let(T.unsafe(nil), String)
