inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable

plugins:
  - rubocop-sorbet

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Sorbet/ValidSigil:
  Enabled: true
  MinimumStrictness: "true"
  Include:
    - "app/**/*.rb"

Sorbet/FalseSigil:
  Enabled: true
  Exclude:
    - "app/**/*.rb"
